apiVersion: v1
kind: ConfigMap
metadata:
  name: service-coog-config
data:
  COOG_URL: "http://{{ .Release.Name }}-{{ .Chart.Name }}-coog"
  COOG_DB_NAME: "{{ .Values.coog.postgres.database }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-security-config
data:
  JWT_INTERNAL_ENCRYPTION: "{{ .Values.jwt.internal.encryption }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-mongo-config
data:
  MONGO_USER: "{{ .Values.gateway.mongodb_user }}"
  MONGO_PASSWORD: "{{ .Values.gateway.mongodb_root_password }}"
  {{- if not .Values.gateway.external_mongodb.enabled }}
  MONGO_HOST: "{{ .Release.Name }}-mongodb"
  {{ else }}
  MONGO_HOST: "{{ .Values.gateway.external_mongodb.host }}"
  {{- end }}
  {{- if not .Values.gateway.external_mongodb.enabled }}
  MONGO_PORT: "{{ .Values.mongodb.service.port }}"
  {{ else }}
  MONGO_PORT: "{{ .Values.gateway.external_mongodb.port }}"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-document-config
data:
  MAX_LIMIT_FILE_SIZE_UPLOAD: "{{ .Values.gateway.document.document_limit }}"
